#!bash

set -ue

cd $(dirname "$0")

if ! [[ -d venv ]]; then
  echo Installing fava ...
  python3 -m venv venv
  venv/bin/pip3 install -r requirements.txt
fi

set -x
exec venv/bin/fava ./main.beancount "$@"
